CREATE TABLE ingredients(
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  name TEXT NOT NULL,
                  type int NOT NULL,
                  UNIQUE(name),
                  FOREIGN KEY (type) REFERENCES ingredientTypes(id) ON DELETE CASCADE
                 );

INSERT INTO ingredients VALUES(1,'abricot',1);
INSERT INTO ingredients VALUES(2,'ail',1);
INSERT INTO ingredients VALUES(3,'amande',1);
INSERT INTO ingredients VALUES(4,'ananas',1);
INSERT INTO ingredients VALUES(5,'artichaut',1);
INSERT INTO ingredients VALUES(6,'asperge',1);
INSERT INTO ingredients VALUES(7,'aubergine',1);
INSERT INTO ingredients VALUES(8,'avocat',1);
INSERT INTO ingredients VALUES(9,'banane',1);
INSERT INTO ingredients VALUES(10,'bette',1);
INSERT INTO ingredients VALUES(11,'betterave rouge',1);
INSERT INTO ingredients VALUES(12,'brocoli',1);
INSERT INTO ingredients VALUES(13,'carotte',1);
INSERT INTO ingredients VALUES(14,'cassis',1);
INSERT INTO ingredients VALUES(15,'céleri',1);
INSERT INTO ingredients VALUES(16,'cerise',1);
INSERT INTO ingredients VALUES(17,'châtaigne',1);
INSERT INTO ingredients VALUES(18,'chou blanc',1);
INSERT INTO ingredients VALUES(19,'chou de bruxelles',1);
INSERT INTO ingredients VALUES(20,'chou frisé',1);
INSERT INTO ingredients VALUES(21,'chou romanesco',1);
INSERT INTO ingredients VALUES(22,'chou rouge',1);
INSERT INTO ingredients VALUES(23,'chou-chinois',1);
INSERT INTO ingredients VALUES(24,'chou-fleur',1);
INSERT INTO ingredients VALUES(25,'chou-rave',1);
INSERT INTO ingredients VALUES(26,'citron',1);
INSERT INTO ingredients VALUES(27,'citron vert',1);
INSERT INTO ingredients VALUES(28,'citrouille',1);
INSERT INTO ingredients VALUES(29,'clémentine',1);
INSERT INTO ingredients VALUES(30,'coing',1);
INSERT INTO ingredients VALUES(31,'concombre',1);
INSERT INTO ingredients VALUES(32,'courge',1);
INSERT INTO ingredients VALUES(33,'courgette',1);
INSERT INTO ingredients VALUES(34,'cresson',1);
INSERT INTO ingredients VALUES(35,'datte',1);
INSERT INTO ingredients VALUES(36,'endive',1);
INSERT INTO ingredients VALUES(37,'epinard',1);
INSERT INTO ingredients VALUES(38,'fenouil',1);
INSERT INTO ingredients VALUES(39,'figue',1);
INSERT INTO ingredients VALUES(40,'fraise',1);
INSERT INTO ingredients VALUES(41,'fraise des bois',1);
INSERT INTO ingredients VALUES(42,'framboise',1);
INSERT INTO ingredients VALUES(43,'fruits',1);
INSERT INTO ingredients VALUES(44,'fruit de la passion',1);
INSERT INTO ingredients VALUES(45,'grenade',1);
INSERT INTO ingredients VALUES(46,'groseille',1);
INSERT INTO ingredients VALUES(47,'haricot',1);
INSERT INTO ingredients VALUES(48,'kaki',1);
INSERT INTO ingredients VALUES(49,'kiwi',1);
INSERT INTO ingredients VALUES(50,'kiwi jaune',1);
INSERT INTO ingredients VALUES(51,'kumquat',1);
INSERT INTO ingredients VALUES(52,'laitue',1);
INSERT INTO ingredients VALUES(53,'salade',1);
INSERT INTO ingredients VALUES(54,'litchi',1);
INSERT INTO ingredients VALUES(55,'mâche',1);
INSERT INTO ingredients VALUES(56,'maïs',1);
INSERT INTO ingredients VALUES(57,'mandarine',1);
INSERT INTO ingredients VALUES(58,'mangue',1);
INSERT INTO ingredients VALUES(59,'marron',1);
INSERT INTO ingredients VALUES(60,'melon',1);
INSERT INTO ingredients VALUES(61,'mirabelle',1);
INSERT INTO ingredients VALUES(62,'mûre',1);
INSERT INTO ingredients VALUES(63,'myrtille',1);
INSERT INTO ingredients VALUES(64,'navet',1);
INSERT INTO ingredients VALUES(65,'nectarine',1);
INSERT INTO ingredients VALUES(66,'noisette',1);
INSERT INTO ingredients VALUES(67,'noix',1);
INSERT INTO ingredients VALUES(68,'oignon',1);
INSERT INTO ingredients VALUES(69,'oignon blanc',1);
INSERT INTO ingredients VALUES(70,'oignon rouge',1);
INSERT INTO ingredients VALUES(71,'orange',1);
INSERT INTO ingredients VALUES(72,'orange sanguine',1);
INSERT INTO ingredients VALUES(73,'pamplemousse',1);
INSERT INTO ingredients VALUES(74,'panais',1);
INSERT INTO ingredients VALUES(75,'papaye',1);
INSERT INTO ingredients VALUES(76,'pastèque',1);
INSERT INTO ingredients VALUES(77,'patate',1);
INSERT INTO ingredients VALUES(78,'pêche',1);
INSERT INTO ingredients VALUES(79,'petit pois',1);
INSERT INTO ingredients VALUES(80,'poire',1);
INSERT INTO ingredients VALUES(81,'poireau',1);
INSERT INTO ingredients VALUES(82,'poivron',1);
INSERT INTO ingredients VALUES(83,'poivron rouge',1);
INSERT INTO ingredients VALUES(84,'poivron vert',1);
INSERT INTO ingredients VALUES(85,'pomme',1);
INSERT INTO ingredients VALUES(86,'pomme de terre',1);
INSERT INTO ingredients VALUES(87,'potimarron',1);
INSERT INTO ingredients VALUES(88,'potiron',1);
INSERT INTO ingredients VALUES(89,'prune',1);
INSERT INTO ingredients VALUES(90,'quetsche',1);
INSERT INTO ingredients VALUES(91,'radis',1);
INSERT INTO ingredients VALUES(92,'raisin',1);
INSERT INTO ingredients VALUES(93,'rhubarbe',1);
INSERT INTO ingredients VALUES(94,'salsifis',1);
INSERT INTO ingredients VALUES(95,'tomate',1);
INSERT INTO ingredients VALUES(96,'tomate cerises',1);
INSERT INTO ingredients VALUES(97,'tomate coeur de boeuf',1);
INSERT INTO ingredients VALUES(98,'topinambour',1);

INSERT INTO ingredients VALUES(99,'steak hachés',2);
INSERT INTO ingredients VALUES(100,'bavette',2);
INSERT INTO ingredients VALUES(101,'entrecôte',2);
INSERT INTO ingredients VALUES(102,'filet mignon',2);
INSERT INTO ingredients VALUES(103,'côte de porc',2);
INSERT INTO ingredients VALUES(104,'filet de poulet',2);
INSERT INTO ingredients VALUES(105,'aiguellettes de poulet',2);
INSERT INTO ingredients VALUES(106,'poulet entier',2);
INSERT INTO ingredients VALUES(107,'escalope de dinde',2);
INSERT INTO ingredients VALUES(108,'ribs',2);
INSERT INTO ingredients VALUES(109,'viande hachée',2);

INSERT INTO ingredients VALUES(110,'jambon de bayonne',3);
INSERT INTO ingredients VALUES(111,'jambon sec',3);
INSERT INTO ingredients VALUES(112,'lonzo de corse',3);
INSERT INTO ingredients VALUES(113,'noix de jambon',3);
INSERT INTO ingredients VALUES(114,'echine de porc',3);
INSERT INTO ingredients VALUES(115,'jambon',3);
INSERT INTO ingredients VALUES(116,'jambon blanc',3);
INSERT INTO ingredients VALUES(117,'saucisson sec',3);
INSERT INTO ingredients VALUES(118,'chorizo',3);
INSERT INTO ingredients VALUES(119,'rosette',3);
INSERT INTO ingredients VALUES(120,'saucisson à l’ail',3);
INSERT INTO ingredients VALUES(121,'saucisson',3);
INSERT INTO ingredients VALUES(122,'saucisse',3);
INSERT INTO ingredients VALUES(123,'chipolatas',3);
INSERT INTO ingredients VALUES(124,'chipolatas aux herbes',3);
INSERT INTO ingredients VALUES(125,'saucisse de toulouse',3);
INSERT INTO ingredients VALUES(126,'saucisse de strasbourg',3);
INSERT INTO ingredients VALUES(127,'saucisse de montbéliard',3);
INSERT INTO ingredients VALUES(128,'saucisse de francfort',3);
INSERT INTO ingredients VALUES(129,'merguez',3);
INSERT INTO ingredients VALUES(130,'andouille',3);
INSERT INTO ingredients VALUES(131,'andouillette',3);
INSERT INTO ingredients VALUES(132,'boudin noir',3);
INSERT INTO ingredients VALUES(133,'boudin blanc',3);
INSERT INTO ingredients VALUES(134,'canard confit',3);
INSERT INTO ingredients VALUES(135,'magret séché',3);
INSERT INTO ingredients VALUES(136,'rillettes du mans',3);
INSERT INTO ingredients VALUES(137,'pâté de campagne',3);
INSERT INTO ingredients VALUES(138,'terrine de campagne',3);
INSERT INTO ingredients VALUES(139,'lardons',3);
INSERT INTO ingredients VALUES(140,'allumettes fumées',3);
INSERT INTO ingredients VALUES(141,'foie gras',3);
INSERT INTO ingredients VALUES(142,'coppa',3);
INSERT INTO ingredients VALUES(143,'saucisse de morteau',3);
INSERT INTO ingredients VALUES(144,'lard fumé',3);
INSERT INTO ingredients VALUES(145,'poitrine de porc salée',3);
INSERT INTO ingredients VALUES(146,'poitrine fumée',3);
INSERT INTO ingredients VALUES(147,'grillon charentais',3);
INSERT INTO ingredients VALUES(148,'pavé au poivre',3);
INSERT INTO ingredients VALUES(149,'bacon',3);
INSERT INTO ingredients VALUES(150,'pancetta',3);

INSERT INTO ingredients VALUES(151,'dorade',4);
INSERT INTO ingredients VALUES(152,'thon',4);
INSERT INTO ingredients VALUES(153,'pavé de saumon',4);
INSERT INTO ingredients VALUES(154,'saumon entier',4);
INSERT INTO ingredients VALUES(155,'saumon fumé',4);
INSERT INTO ingredients VALUES(156,'cabillaud',4);
INSERT INTO ingredients VALUES(157,'crevettes rose',4);
INSERT INTO ingredients VALUES(158,'moules',4);
INSERT INTO ingredients VALUES(159,'huitres',4);

INSERT INTO ingredients VALUES(160,'lait',5);
INSERT INTO ingredients VALUES(161,'beurre',5);
INSERT INTO ingredients VALUES(162,'beurre demi-sel',5);
INSERT INTO ingredients VALUES(163,'oeufs',5);
INSERT INTO ingredients VALUES(164,'pate brisée',5);
INSERT INTO ingredients VALUES(165,'pate sablée',5);
INSERT INTO ingredients VALUES(166,'pate feuilleté',5);
INSERT INTO ingredients VALUES(167,'pate à pizza',5);
INSERT INTO ingredients VALUES(168,'raviolis',5);
INSERT INTO ingredients VALUES(169,'pates fraiches',5);
INSERT INTO ingredients VALUES(170,'crème fraiche',5);
INSERT INTO ingredients VALUES(171,'crème fraiche entière',5);
INSERT INTO ingredients VALUES(172,'crème fleurette',5);
INSERT INTO ingredients VALUES(173,'crème liquide',5);
INSERT INTO ingredients VALUES(174,'crème liquide entière',5);
INSERT INTO ingredients VALUES(175,'chantilly',5);
INSERT INTO ingredients VALUES(176,'crème végétal',5);
INSERT INTO ingredients VALUES(177,'lait d’amande',5);
INSERT INTO ingredients VALUES(178,'lait d’avoine',5);
INSERT INTO ingredients VALUES(179,'lait de riz',5);
INSERT INTO ingredients VALUES(180,'lait de coco',5);
INSERT INTO ingredients VALUES(181,'gaspacho',5);

INSERT INTO ingredients VALUES(182,'glaces',6);
INSERT INTO ingredients VALUES(183,'frites',6);
INSERT INTO ingredients VALUES(184,'petis pois surgelés',6);
INSERT INTO ingredients VALUES(185,'steaks surgelés',6);
INSERT INTO ingredients VALUES(186,'poelée de légume surgelées',6);
INSERT INTO ingredients VALUES(187,'plat surgelé',6);
INSERT INTO ingredients VALUES(188,'fruits surgelés',6);
INSERT INTO ingredients VALUES(189,'fraises surgelées',6);
INSERT INTO ingredients VALUES(190,'mangue surgelée',6);
INSERT INTO ingredients VALUES(191,'fondant au chocolat surgelés',6);

INSERT INTO ingredients VALUES(192,'chèvre',7);
INSERT INTO ingredients VALUES(193,'chèvre frais',7);
INSERT INTO ingredients VALUES(194,'crotin de chèvre',7);
INSERT INTO ingredients VALUES(195,'buche de chèvre',7);
INSERT INTO ingredients VALUES(196,'beaufort',7);
INSERT INTO ingredients VALUES(197,'gruyère',7);
INSERT INTO ingredients VALUES(198,'gruyère rapé',7);
INSERT INTO ingredients VALUES(199,'comté',7);
INSERT INTO ingredients VALUES(200,'mozzarella',7);
INSERT INTO ingredients VALUES(201,'madame loïc',7);
INSERT INTO ingredients VALUES(202,'fromage à raclette',7);
INSERT INTO ingredients VALUES(203,'saint félicien',7);
INSERT INTO ingredients VALUES(204,'camembert',7);
INSERT INTO ingredients VALUES(205,'reblochon',7);
INSERT INTO ingredients VALUES(206,'caprice des dieux',7);
INSERT INTO ingredients VALUES(207,'rocamadour',7);
INSERT INTO ingredients VALUES(208,'cabécoufromage à burgers',7);
INSERT INTO ingredients VALUES(209,'parmesan',7);
INSERT INTO ingredients VALUES(210,'roquefort',7);
INSERT INTO ingredients VALUES(211,'boursin',7);
INSERT INTO ingredients VALUES(212,'brie',7);
INSERT INTO ingredients VALUES(213,'kiri',7);
INSERT INTO ingredients VALUES(214,'fromage',7);
INSERT INTO ingredients VALUES(215,'morbier',7);
INSERT INTO ingredients VALUES(216,'tomme de savoie',7);
INSERT INTO ingredients VALUES(217,'vache qui rit',7);

INSERT INTO ingredients VALUES(218,'haricots vert en boite',8);
INSERT INTO ingredients VALUES(219,'haricots rouge  en boite',8);
INSERT INTO ingredients VALUES(220,'flageolets',8);
INSERT INTO ingredients VALUES(221,'petits pois carottes',8);
INSERT INTO ingredients VALUES(222,'petits pois',8);
INSERT INTO ingredients VALUES(223,'sardines en boite',8);
INSERT INTO ingredients VALUES(224,'thon en miette',8);
INSERT INTO ingredients VALUES(225,'maïs en boite',8);
INSERT INTO ingredients VALUES(226,'coeur d’artichaut',8);
INSERT INTO ingredients VALUES(227,'macédoine',8);
INSERT INTO ingredients VALUES(228,'asperges en boite',8);
INSERT INTO ingredients VALUES(229,'dés de tomates',8);
INSERT INTO ingredients VALUES(230,'sauce tomate',8);
INSERT INTO ingredients VALUES(231,'coulis de tomate',8);
INSERT INTO ingredients VALUES(232,'tomates pelées',8);
INSERT INTO ingredients VALUES(233,'mogettes',8);
INSERT INTO ingredients VALUES(234,'maqueraux en boite',8);
INSERT INTO ingredients VALUES(235,'sauce pour pates',8);
INSERT INTO ingredients VALUES(236,'raviolis en boite',8);
INSERT INTO ingredients VALUES(237,'olives noires',8);
INSERT INTO ingredients VALUES(238,'olives vertes',8);

INSERT INTO ingredients VALUES(239,'haricots vert',9);
INSERT INTO ingredients VALUES(240,'haricots rouge',9);
INSERT INTO ingredients VALUES(241,'farfalles',9);
INSERT INTO ingredients VALUES(242,'quinoa',9);
INSERT INTO ingredients VALUES(243,'spaghetti',9);
INSERT INTO ingredients VALUES(244,'coquillettes',9);
INSERT INTO ingredients VALUES(245,'crozets',9);
INSERT INTO ingredients VALUES(246,'lentilles vertes',9);
INSERT INTO ingredients VALUES(247,'lentilles corail',9);
INSERT INTO ingredients VALUES(248,'wraps',9);
INSERT INTO ingredients VALUES(249,'riz',9);
INSERT INTO ingredients VALUES(250,'riz complet',9);
INSERT INTO ingredients VALUES(251,'boulgour',9);
INSERT INTO ingredients VALUES(252,'avoine',9);
INSERT INTO ingredients VALUES(253,'semoule fine',9);
INSERT INTO ingredients VALUES(254,'kit farritas',9);
INSERT INTO ingredients VALUES(255,'kit burritos',9);

INSERT INTO ingredients VALUES(256,'pain',10);
INSERT INTO ingredients VALUES(257,'pain de main',10);
INSERT INTO ingredients VALUES(258,'biscotte',10);
INSERT INTO ingredients VALUES(259,'pain burgers',10);
INSERT INTO ingredients VALUES(260,'pain brioché',10);

INSERT INTO ingredients VALUES(261,'farine de blé',11);
INSERT INTO ingredients VALUES(262,'farine de sarasin',11);
INSERT INTO ingredients VALUES(263,'pépites de chocolat',11);
INSERT INTO ingredients VALUES(264,'farine d’épautre',11);
INSERT INTO ingredients VALUES(265,'panure',11);
INSERT INTO ingredients VALUES(266,'panure panko',11);
INSERT INTO ingredients VALUES(267,'levure chimique',11);
INSERT INTO ingredients VALUES(268,'levure de boulanger',11);
INSERT INTO ingredients VALUES(269,'maïzena (fecule de maïs)',11);
INSERT INTO ingredients VALUES(270,'fécule de pomme de terre',11);

INSERT INTO ingredients VALUES(271,'coriandre',12);
INSERT INTO ingredients VALUES(272,'basilic',12);
INSERT INTO ingredients VALUES(273,'persil',12);
INSERT INTO ingredients VALUES(274,'ciboulette',12);
INSERT INTO ingredients VALUES(275,'garam masala',12);
INSERT INTO ingredients VALUES(276,'anis etoilé',12);
INSERT INTO ingredients VALUES(277,'cannelle',12);
INSERT INTO ingredients VALUES(278,'batonnets de cannelle',12);
INSERT INTO ingredients VALUES(279,'clous de girofle',12);
INSERT INTO ingredients VALUES(280,'cumin en poudre',12);
INSERT INTO ingredients VALUES(281,'graine de cumin',12);
INSERT INTO ingredients VALUES(282,'laurier',12);
INSERT INTO ingredients VALUES(283,'romarin',12);
INSERT INTO ingredients VALUES(284,'menthe',12);
INSERT INTO ingredients VALUES(285,'thym',12);
INSERT INTO ingredients VALUES(286,'aneth',12);
INSERT INTO ingredients VALUES(287,'cardamome',12);
INSERT INTO ingredients VALUES(288,'coriandre séchée',12);
INSERT INTO ingredients VALUES(289,'curcuma',12);
INSERT INTO ingredients VALUES(290,'fève de tonka',12);
INSERT INTO ingredients VALUES(291,'gingembre en poudre',12);
INSERT INTO ingredients VALUES(292,'sel',12);
INSERT INTO ingredients VALUES(293,'poivre',12);
INSERT INTO ingredients VALUES(294,'mélange 3 poivres',12);
INSERT INTO ingredients VALUES(295,'mélange 5 baies',12);
INSERT INTO ingredients VALUES(296,'poivre de sichuan',12);
INSERT INTO ingredients VALUES(297,'noix de muscade',12);
INSERT INTO ingredients VALUES(298,'paprika',12);
INSERT INTO ingredients VALUES(299,'curry',12);
INSERT INTO ingredients VALUES(300,'piment d’espelette',12);
INSERT INTO ingredients VALUES(301,'safran',12);
INSERT INTO ingredients VALUES(302,'ketchup',12);
INSERT INTO ingredients VALUES(303,'moutarde',12);
INSERT INTO ingredients VALUES(304,'tabasco',12);
INSERT INTO ingredients VALUES(305,'wasabi',12);
INSERT INTO ingredients VALUES(306,'harissa',12);
INSERT INTO ingredients VALUES(307,'sauce au poivre',12);
INSERT INTO ingredients VALUES(308,'sauce bbq',12);
INSERT INTO ingredients VALUES(309,'sauce bourguignonne',12);
INSERT INTO ingredients VALUES(310,'sauce aigredouce',12);
INSERT INTO ingredients VALUES(311,'sauce soja salée',12);
INSERT INTO ingredients VALUES(312,'sauce soja sucrée',12);
INSERT INTO ingredients VALUES(313,'huile de colza',12);
INSERT INTO ingredients VALUES(314,'huile de pépin de raison',12);
INSERT INTO ingredients VALUES(315,'huile de tournesol',12);
INSERT INTO ingredients VALUES(316,'huile de friture',12);
INSERT INTO ingredients VALUES(317,'huile d’olive',12);
INSERT INTO ingredients VALUES(318,'huile de sésame',12);
INSERT INTO ingredients VALUES(319,'huile',12);
INSERT INTO ingredients VALUES(320,'vinaigre balsamique',12);
INSERT INTO ingredients VALUES(321,'vinaigre de vin',12);
INSERT INTO ingredients VALUES(322,'vinaigre de cidre',12);
INSERT INTO ingredients VALUES(323,'vinaigre de xérès',12);
INSERT INTO ingredients VALUES(324,'graine de sésame',12);
INSERT INTO ingredients VALUES(325,'bloc curry japonais',12);

INSERT INTO ingredients VALUES(326,'chocolat blanc',13);
INSERT INTO ingredients VALUES(327,'chocolat au lait',13);
INSERT INTO ingredients VALUES(328,'chocolat noir',13);
INSERT INTO ingredients VALUES(329,'confiture de fraise',13);
INSERT INTO ingredients VALUES(330,'confiture de framboise',13);
INSERT INTO ingredients VALUES(331,'confiture',13);
INSERT INTO ingredients VALUES(332,'patatartiner',13);
INSERT INTO ingredients VALUES(333,'gateaux',13);
INSERT INTO ingredients VALUES(334,'cookies',13);
INSERT INTO ingredients VALUES(335,'compote',13);
INSERT INTO ingredients VALUES(336,'ananas au sirop',13);
INSERT INTO ingredients VALUES(337,'barres de céréales',13);
INSERT INTO ingredients VALUES(338,'sucre',13);
INSERT INTO ingredients VALUES(339,'sucre en morceaux',13);
INSERT INTO ingredients VALUES(340,'sucre de coco',13);
INSERT INTO ingredients VALUES(341,'sirop d’agave',13);
INSERT INTO ingredients VALUES(342,'cassonade',13);
INSERT INTO ingredients VALUES(343,'vanille en poudre',13);
INSERT INTO ingredients VALUES(344,'gousse de vanille',13);
INSERT INTO ingredients VALUES(345,'arome fleur d’oranger',13);
INSERT INTO ingredients VALUES(346,'pectine',13);
INSERT INTO ingredients VALUES(347,'sucre vanillé',13);
INSERT INTO ingredients VALUES(348,'sucre glace',13);
INSERT INTO ingredients VALUES(349,'gélatine en poudre',13);
INSERT INTO ingredients VALUES(350,'feuille de gélatine',13);
INSERT INTO ingredients VALUES(351,'thé',13);
INSERT INTO ingredients VALUES(352,'café',13);
INSERT INTO ingredients VALUES(353,'café soluble',13);
INSERT INTO ingredients VALUES(354,'café décaféiné',13);
INSERT INTO ingredients VALUES(355,'cacao en poudre',13);

INSERT INTO ingredients VALUES(356,'jus d’orange',14);
INSERT INTO ingredients VALUES(357,'jus de pomme',14);
INSERT INTO ingredients VALUES(358,'jus multifruits',14);
INSERT INTO ingredients VALUES(359,'jus de raisin',14);
INSERT INTO ingredients VALUES(360,'jus de fruits',14);
INSERT INTO ingredients VALUES(361,'limonade',14);
INSERT INTO ingredients VALUES(362,'coca',14);
INSERT INTO ingredients VALUES(363,'sirop',14);
INSERT INTO ingredients VALUES(364,'bière',14);
INSERT INTO ingredients VALUES(365,'vin blanc',14);
INSERT INTO ingredients VALUES(366,'vin rouge',14);
INSERT INTO ingredients VALUES(367,'vin rosé',14);
INSERT INTO ingredients VALUES(368,'champagne',14);
INSERT INTO ingredients VALUES(369,'saké',14);
INSERT INTO ingredients VALUES(370,'sirop de sucre de canne',14);
INSERT INTO ingredients VALUES(371,'recharge sodastream',14);
INSERT INTO ingredients VALUES(372,'eau en bouteille',14);
INSERT INTO ingredients VALUES(373,'sodas',14);

INSERT INTO ingredients VALUES(374,'liquide vaisselle',15);
INSERT INTO ingredients VALUES(375,'sac poubelle',15);
INSERT INTO ingredients VALUES(376,'savon pour main',15);
INSERT INTO ingredients VALUES(377,'gel douche',15);
INSERT INTO ingredients VALUES(378,'shampoing',15);
INSERT INTO ingredients VALUES(379,'déodorent',15);
INSERT INTO ingredients VALUES(380,'lames rasoir',15);
INSERT INTO ingredients VALUES(381,'démaquillant',15);
INSERT INTO ingredients VALUES(382,'coton',15);
INSERT INTO ingredients VALUES(383,'coton tige',15);
INSERT INTO ingredients VALUES(384,'serviettes hygiéniques',15);
INSERT INTO ingredients VALUES(385,'tampons',15);
INSERT INTO ingredients VALUES(386,'sopalin',15);
INSERT INTO ingredients VALUES(387,'mouchoirs',15);
INSERT INTO ingredients VALUES(388,'boite de mouchoir',15);
INSERT INTO ingredients VALUES(389,'piles AA',15);
INSERT INTO ingredients VALUES(390,'pile AAA',15);
INSERT INTO ingredients VALUES(391,'éponges',15);
INSERT INTO ingredients VALUES(392,'pastilles lave-vaisselle',15);
INSERT INTO ingredients VALUES(393,'pastilles lave-linge',15);
INSERT INTO ingredients VALUES(394,'détachant',15);
INSERT INTO ingredients VALUES(395,'adoussissant',15);
INSERT INTO ingredients VALUES(396,'lingettes désinfectantes',15);
INSERT INTO ingredients VALUES(397,'lingettes couleurs',15);
INSERT INTO ingredients VALUES(398,'deboucheur canalisation',15);
